import {BundleProps} from '../bundles-carousel';

export const items: BundleProps[] = [
  {
    title: 'Complete Sleep Bundle',
    description: 'Cognitive Function, Mood Regulation, Sleep Quality',
    image: '/assets/bundles/3.png',
    tags: ['GMO Free', 'Gluten Free', 'Vegan', 'Dairy Free'],
    rating: 5,
    category: 'Sleep',
  },
  {
    title: 'Melatonin Support Bundle',
    description: 'Natural Sleep Aid, Relaxation',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Sleep',
  },
  {
    title: 'Advanced Sleep Formula',
    description: 'Deep Sleep, Recovery Support',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 4,
    category: 'Sleep',
  },
  {
    title: 'Sleep Essentials Kit',
    description: 'Starter Sleep Support Package',
    image: '/assets/bundles/1.png',
    tags: ['Vegan', 'Dairy Free'],
    rating: 4,
    category: 'Sleep',
  },
  {
    title: 'Relaxation Sleep Bundle',
    description: 'Stress Relief, Better Sleep',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Sleep',
  },
  {
    title: 'Sleep & Recovery Formula',
    description: 'Athlete Recovery, Deep Sleep',
    image: '/assets/bundles/3.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 5,
    category: 'Sleep',
  },
  {
    title: 'Sleep Maintenance Bundle',
    description: 'Uninterrupted Sleep Support',
    image: '/assets/bundles/1.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 4,
    category: 'Sleep',
  },
  {
    title: 'Premium Sleep Stack',
    description: 'Comprehensive Sleep Formula',
    image: '/assets/bundles/4.png',
    tags: ['Dairy Free', 'GMO Free'],
    rating: 5,
    isNew: true,
    category: 'Sleep',
  },
  {
    title: 'Focus & Clarity Bundle',
    description: 'Mental Performance, Cognitive Support',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Cognitive Function',
  },
  {
    title: 'Memory Support Formula',
    description: 'Brain Health, Recall Enhancement',
    image: '/assets/bundles/1.png',
    tags: ['Gluten Free', 'Dairy Free'],
    rating: 4,
    category: 'Cognitive Function',
  },
  {
    title: 'Cognitive Longevity Stack',
    description: 'Brain Health, Anti-Aging Support',
    image: '/assets/bundles/1.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Cognitive Function',
  },
  {
    title: 'Nootropic Performance Bundle',
    description: 'Mental Clarity, Focus Enhancement',
    image: '/assets/bundles/4.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 5,
    category: 'Cognitive Function',
  },
  {
    title: 'Brain Fog Relief Stack',
    description: 'Mental Clarity, Cognitive Function',
    image: '/assets/bundles/3.png',
    tags: ['Dairy Free', 'GMO Free'],
    rating: 4,
    category: 'Cognitive Function',
  },
  {
    title: 'Executive Function Support',
    description: 'Decision Making, Mental Processing',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Cognitive Function',
  },
  {
    title: 'Study & Focus Formula',
    description: 'Concentration, Learning Support',
    image: '/assets/bundles/1.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 5,
    isNew: true,
    category: 'Cognitive Function',
  },
  {
    title: 'Cognitive Recovery Bundle',
    description: 'Mental Fatigue, Stress Recovery',
    image: '/assets/bundles/4.png',
    tags: ['Gluten Free', 'GMO Free'],
    rating: 4,
    category: 'Cognitive Function',
  },
  {
    title: 'Male Hormone Support Bundle',
    description: 'Hormone Support, Foundational Health',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Gluten Free', 'Dairy Free'],
    rating: 5,
    category: 'Foundational Health',
  },
  {
    title: 'Daily Essentials Pack',
    description: 'Comprehensive Vitamin Support',
    image: '/assets/bundles/3.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Foundational Health',
  },
  {
    title: 'Gut Health Formula',
    description: 'Digestive Support, Microbiome Health',
    image: '/assets/bundles/3.png',
    tags: ['Gluten Free', 'Dairy Free'],
    rating: 4,
    category: 'Foundational Health',
  },
  {
    title: 'Immune Defense Bundle',
    description: 'Immune System, Resistance Support',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Foundational Health',
  },
  {
    title: 'Longevity Support Stack',
    description: 'Anti-Aging, Cellular Health',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Foundational Health',
  },
  {
    title: 'Energy & Vitality Formula',
    description: 'Daily Energy, Stamina Support',
    image: '/assets/bundles/4.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 4,
    category: 'Foundational Health',
  },
  {
    title: 'Joint & Mobility Bundle',
    description: 'Joint Health, Movement Support',
    image: '/assets/bundles/1.png',
    tags: ['Dairy Free', 'GMO Free'],
    rating: 5,
    category: 'Foundational Health',
  },
  {
    title: 'Heart Health Essentials',
    description: 'Cardiovascular Support, Circulation',
    image: '/assets/bundles/3.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    isNew: true,
    category: 'Foundational Health',
  },
  {
    title: 'PR Lotion Starter Kit',
    description: 'Athletic Performance, Muscle Recovery',
    image: '/assets/bundles/4.png',
    tags: ['Vegan', 'Dairy Free'],
    rating: 5,
    isNew: true,
    category: 'Athletic Performance',
  },
  {
    title: 'Pre-Workout Performance',
    description: 'Energy, Focus, Pump Support',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Athletic Performance',
  },
  {
    title: 'Post-Workout Recovery',
    description: 'Recovery, Muscle Growth Support',
    image: '/assets/bundles/3.png',
    tags: ['Gluten Free', 'Dairy Free'],
    rating: 4,
    category: 'Athletic Performance',
  },
  {
    title: 'Endurance Bundle',
    description: 'Stamina, Aerobic Performance',
    image: '/assets/bundles/1.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Athletic Performance',
  },
  {
    title: 'Strength Training Stack',
    description: 'Muscle Growth, Strength Support',
    image: '/assets/bundles/1.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Athletic Performance',
  },
  {
    title: 'Joint Support for Athletes',
    description: 'Joint Health, Mobility Enhancement',
    image: '/assets/bundles/1.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 4,
    category: 'Athletic Performance',
  },
  {
    title: 'Hydration Performance Pack',
    description: 'Electrolytes, Hydration Support',
    image: '/assets/bundles/1.png',
    tags: ['Dairy Free', 'GMO Free'],
    rating: 5,
    category: 'Athletic Performance',
  },
  {
    title: 'Athletic Recovery Formula',
    description: 'Comprehensive Recovery Support',
    image: '/assets/bundles/4.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Athletic Performance',
  },
  {
    title: 'Tongkat & Fadogia 60 Day Supply',
    description: 'Hormone Support',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Dairy Free'],
    rating: 5,
    isBestseller: true,
    category: 'Hormone Support',
  },
  {
    title: "Women's Hormone Balance",
    description: 'Female Hormone Support, Wellness',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Hormone Support',
  },
  {
    title: 'Thyroid Support Formula',
    description: 'Metabolism, Energy, Thyroid Health',
    image: '/assets/bundles/2.png',
    tags: ['Gluten Free', 'Dairy Free'],
    rating: 4,
    category: 'Hormone Support',
  },
  {
    title: 'Stress Hormone Support',
    description: 'Cortisol Balance, Stress Relief',
    image: '/assets/bundles/3.png',
    tags: ['GMO Free', 'Vegan'],
    rating: 5,
    category: 'Hormone Support',
  },
  {
    title: 'Testosterone Support Bundle',
    description: 'Male Hormone Optimization',
    image: '/assets/bundles/1.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    category: 'Hormone Support',
  },
  {
    title: 'Estrogen Balance Formula',
    description: "Hormone Regulation, Women's Health",
    image: '/assets/bundles/4.png',
    tags: ['Vegan', 'GMO Free'],
    rating: 4,
    category: 'Hormone Support',
  },
  {
    title: 'Adrenal Support Stack',
    description: 'Adrenal Health, Energy Balance',
    image: '/assets/bundles/3.png',
    tags: ['Dairy Free', 'GMO Free'],
    rating: 5,
    category: 'Hormone Support',
  },
  {
    title: 'Complete Hormone Balance',
    description: 'Full-Spectrum Hormone Support',
    image: '/assets/bundles/2.png',
    tags: ['GMO Free', 'Gluten Free'],
    rating: 5,
    isNew: true,
    category: 'Hormone Support',
  },
] as const;
